### ISSUE TITLE
Could not load gfx.wad (missing wad) (Citra Emulator)

### ISSUE THREAD

**Issue by PerikiyoXD** [masterfeizz/ctrQuake#1]
(Testing with Citra Emulator)

Seems that there are some missing files. Do I have to download shareware Quake? Because pak0.pak used is Shareware one, but without some files.

**Comment by PerikiyoXD** [comment]
The pop.lmp file seems to be a license file, ignoring as it triggers the Shareware version.
By the other hand, gfx.wad is missing.

**Comment by masterfeizz** [comment]
You are getting this error because of the way you are launching the game in citra. If you are dragging the file into the citra executable, the id1 folder must be in the root directory of the sdmc

**Comment by PerikiyoXD** [comment]
I thought there was a virtual sdmc on the loaded "game" folder. Now you could close the issue.
