### ISSUE TITLE
Screens don't turn back on after closing lid

### ISSUE THREAD

**Issue by ElderCub** [masterfeizz/ctrQuake#4]
Using an N3DS 10.3.0-28U with menuhax, I was not able to continue playing the game after closing and reopening the lid. I can still hear my weapon fire and jumping when pressing buttons, but I couldn't seen anything. The lcd was black and the backlights were off.

**Comment by ElderCub** [comment]
Apparantly this is an issue with homebrewing itself, a work around is to press the home button before loading a homebrew.

**Comment by masterfeizz** [comment]
Yes, this is problem with some entry points and launchers. Some users reported the issues while some, including me, never ran into it.
