### ISSUE TITLE
[Question] How to install new levels?

### ISSUE THREAD

**Issue by alexisbietti** [masterfeizz/ctrQuake#7]
Hi, id released a new Quake level, is it possible to install and play it on ctrQuake?

https://twitter.com/machinegames/status/746363189768650752 

Thanks

**Comment by masterfeizz** [comment]
I haven't tested it myself, but to launch the episode you need to follow these steps:
Create a "dopa" folder in your ctrQuake directory
Extract the pak0.pak file to the new folder (/3ds/ctrQuake/dopa)
Then create a .xml shortcut (/3ds/dopa.xml) with the following content

``` xml
<shortcut>
    <name>Dimension of the past</name>
    <executable>/3ds/ctrQuake/ctrQuake.3dsx</executable>
    <arg>-game dopa</arg>
</shortcut>
```

Launch it from the Homebrew launcher

**Comment by alexisbietti** [comment]
Thanks! I created the shortcut, unfortunately it fails with "Model progs/enforcer.mdl not found"...

From there, it seems impossible to stop the application, a reboot is the only way out.

Cheers
